version: '3'
services:
  
  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - lamp-docker
  
  
  www:
    depends_on:
      - db
    #image: php:8.1-apache
    build: './'
    volumes:
      - "./www:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_POST=3306
    networks:
      - lamp-docker      

  adminer:
    depends_on:
    - db
    image: adminer
    restart: always
    ports:
      - 8002:8080
    networks:
      - lamp-docker     


networks:
  lamp-docker:
    driver: bridge
